---
title: "Project 1: Summarizing the main sources of variability in the way people solve their data cleaning final project"
author: "Andrew Leroux"
date: "9/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Methods

# Data Location

Note: This is an initial pass. Depending on how many "non-standard" file paths I run into, I may hav eto revise this portion 
of the data retrieval process. 
I have seen at least one student (Benjamin Chan) who put most of their R code into a their Markdown document, then simply 
sourced this document with their "run_analysis.R" file.


The data will be retrieved from the github repo linked by Jeff (http://jtleek.com/advdatasci/).
The analysis will be performed on individuals "run_analysis.R" files. 
The code checks for non-standard capitalization (i.e. Run vs RUN vs run). 
To find these files, we do an exhaustive check of folder pathways in individuals' repositories. 

# Data Retrieval 




## Scientific Question

Ultimately, I think the scientific question we're asking here is how can we quantify the differences in the way 
people write code.

## Current plan of attack

It seems to me like a logical place to start in terms of explaining the variability in how individuals solved this 
problem will be in the number of function calls they made, as well as the number of different functions they used, 
what packages these functions are associated with, and the "intended use" of said functions. 
To identify these patterns we can use do some fairly straightforward regular expression parsing. 
Depending on the number of unique functions 